config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :bikes do
    resources :parts
  end

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
    has_many :parts, dependent: :destroy
    validates :maker, presence: true,
                      length: { minimum: 2}
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :bike
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
    http_basic_authenticate_with name: "dhh",
      password: "secret", except: [:index, :show]
    def index
        @bike = Bike.all
    end

    def edit
        @bike = Bike.find(params[:id])
    end

    def show
        @bike = Bike.find(params[:id])
    end

    def new
        @bike = Bike.new
    end

    def create
      @bike = Bike.new(bike_params)

      if @bike.save
        redirect_to @bike
      else
        render 'new'
      end
    end

    def update
      @bike = Bike.find(params[:id])

      if @bike.update(bike_params)
        redirect_to @bike
      else
        render 'edit'
      end
    end

    def destroy
        @bike = Bike.find(params[:id])
        @bike.destroy

        redirect_to bikes_path
    end

    private
      def bike_params
        params.require(:bike).permit(:maker,:machine_name)
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
    http_basic_authenticate_with name: "dhh",
      password: "secret", only: :destroy
    def create
        @bike = Bike.find(params[:bike_id])
        @parts = @bike.parts.create(part_params)
        redirect_to bike_path(@bike)
    end

    def destroy
        @bike = Bike.find(params[:bike_id])
        @part = @bike.parts.find(params[:id])
        @part.destroy
        redirect_to bike_path(@bike)
    end

    private
      def part_params
        params.require(:part).permit(:parts_name)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/bikes/_form.html.erb
<%= form_with model: @bike, local: true do |form| %>
    <% if @bike.errors.any? %>
    <div id="error_explanation">
    <h2><%= pluralize(@bike.errors.count, "error")%>
    prohibited
    this article from being saved:</h2>
    <ul>
    <% @bike.errors.full_messages.each do |msg| %>
      <li><%= msg%></li>
    <% end %>
    </ul>
    <% end %>
    <p>
      <%= form.label :maker %><br>
      <%= form.text_field :maker %>
    </p>
    <p>
      <%= form.label :machine_name %><br>
      <%= form.text_area :machine_name %>
    </p>

    <p>
      <%= form.submit %>
    </p>
<% end %>

app/views/bikes/edit.html.erb
<h1>バイクを編集するだっちゃ！</h1>

<%= render 'form' %>

<%= link_to 'Back', bikes_path %>

app/views/bikes/index.html.erb
<h1>バイク達だっ！</h1>
<%= link_to 'My Bike', controller: 'bikes' %>
<%= link_to 'New Bike', new_bike_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @bike.each do |bike| %>
    <tr>
      <td><%= bike.maker %></td>
      <td><%= bike.machine_name %></td>
      <td><%= link_to 'Show', bike_path(bike) %></td>
      <td><%= link_to 'Edit', edit_bike_path(bike) %></td>
      <td><%= link_to 'Destroy', bike_path(bike),
        method: :delete, data: { confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
</table>

app/views/bikes/new.html.erb
<h1>バイクを登録するだっちゃ！</h1>

<%= render 'form' %>

<%= link_to 'Back', bikes_path %>

app/views/bikes/show.html.erb
<p>
  <strong>Maker:</strong>
  <%= @bike.maker %>
</p>
<p>
  <strong>MachineName:</strong>
  <%= @bike.machine_name %>
</p>

<h2>パーツだぞー</h2>
<%= render @bike.parts %>

<h2>Add a parts:</h2>
<%= render "parts/form" %>

<%= link_to 'Back', bikes_path %>
| <%= link_to 'Edit', edit_bike_path(@bike)%>

app/views/home/index.html.erb
<h1>ツーリングすっぞ！</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Toumatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parts/_form.html.erb
<%= form_with(model: [ @bike, @bike.parts.build ], local: true) do |form| %>
  <p>
    <%= form.label :parts_name %><br>
    <%= form.text_field :parts_name %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/parts/_part.html.erb
<p>
    <strong>パーツ</strong>
    <%= part.parts_name %>
</p>

<p>
  <%= link_to 'Destroy Parts', [part.bike, part],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>